VERSION := 1.0

docker.run:
    docker run -d --rm -p 8000:8000 --name server-{VERSION} lighter0125/gloo:${VERSION}

docker.debug:
    docker exec -it server /bin/bash

docker.log:
    docker logs server